---
title: "Simpsons_Emery_cooking"
author: "Emery Lauer"
date: "2025-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
install.packages("plotly")
```

## EDA

```{r}
df_ep <- read.csv("data/simpsons_episodes.csv")
df_script <- read.csv("data/simpsons_script_lines.csv")

head(df_ep)
head(df_script)

```

```{r}
df_script %>% 
  filter(speaking_line == TRUE) %>% 
  filter(episode_id == 1) %>% 
  filter(word_count <= 1000) %>% 
  mutate(word_count = as.numeric(word_count)) %>% 
  group_by(raw_character_text) %>% 
  summarize(total_word_count = sum(word_count)) %>% 
  slice_max(total_word_count, n = 6) %>% 
  arrange(desc(total_word_count)) 

```

```{r}
get_word_counts_per_episode <- function(df_script) {
  df_script %>%
    filter(speaking_line == TRUE) %>%
    mutate(
      word_count = (as.numeric(word_count))
    ) %>%
    filter(!is.na(word_count)) %>%
    filter(word_count <= 1000) %>% 
    group_by(episode_id, raw_character_text) %>%
    summarize(total_word_count = sum(word_count), .groups = "drop") %>%
    group_by(episode_id) %>%
    slice_max(total_word_count, n = 1, with_ties = FALSE) %>%
    arrange(episode_id, desc(total_word_count))
}

episode_word_counts <- get_word_counts_per_episode(df_script)
episode_word_counts

```

```{r}
 df_ep_new <- df_ep %>% 
  select(id, imdb_votes, original_air_date, original_air_year, us_viewers_in_millions, views) %>% 
  rename(
    episode_id = id
  )


df_simpsons <- df_ep_new %>%
  left_join(episode_word_counts, by = "episode_id")

df_simpsons
```

```{r}
# Bart|Homer|Marge|Lisa|Maggie|
df_simpsons %>% 
  filter(grepl("Simpson|Santa's Little Helper|Obama|Trump|Millhouse|Chief Wiggum", raw_character_text)) %>% 
ggplot(
    aes(x = `episode_id`, y = us_viewers_in_millions, color = raw_character_text)
  ) +
  geom_point() 
# labs(
#   title = "Serotonin Levels vs. # of Friends",
#   x = "Number of Friends",
#   y = "Serotonin (ng/mL)",
# )
```

```{r}
df_simpsons %>% 
  filter(grepl("Simpson|Santa's Little Helper|Obama|Trump|Millhouse|Chief Wiggum", raw_character_text)) %>% 
ggplot(
    aes(x = `original_air_year`, y = us_viewers_in_millions, color = raw_character_text)
  ) +
  geom_count() +
  theme(axis.text.x = element_text(angle = 50, hjust = 1))
# labs(
#   title = "Serotonin Levels vs. # of Friends",
#   x = "Number of Friends",
#   y = "Serotonin (ng/mL)",
# )
```

```{r}
df_simpsons %>% 
  filter(grepl("Simpson|Santa's Little Helper|Obama|Trump|Millhouse|Chief Wiggum", raw_character_text)) %>% 
  mutate(votes_per_view = imdb_votes/us_viewers_in_millions) %>% 
ggplot(
    aes(x = `episode_id`, y = votes_per_view, color = raw_character_text)
    )+
  geom_point() +
  geom_smooth(color = "yellow")+
  theme(axis.text.x = element_text(angle = 50, hjust = 1))
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
